# Generated by Django 4.1.7 on 2023-03-10 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_access_code',
            name='id',
            field=models.UUIDField(db_column='Personal access code', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
